"""Parity tests — compare v3 output against v2 golden baseline per scenario.

Each scenario folder has:
  golden/  — normalized v2 output (generated by run_parity.py --v2-only)
  v3/      — normalized v3 output (generated by run_parity.py --v3-only)

Run:
  uv run pytest tests/parity/ -v
"""

from __future__ import annotations

import glob as _glob
import importlib.util
import json
import os
from pathlib import Path

import pytest

try:
    from .parity_entities import ENTITY_TO_TYPENAME, ENTITY_TYPES
except ImportError:
    from parity_entities import ENTITY_TO_TYPENAME, ENTITY_TYPES

PARITY_DIR = Path(__file__).parent
OUTPUT_DIR = PARITY_DIR / "output"
INTEGRATION_DIR = PARITY_DIR.parent / "integration"
CANONICAL_CONNECTION_QN = "default/mysql/__PARITY__"

VOLATILE_FIELDS = {"lastSyncWorkflowName", "lastSyncRun", "lastSyncRunAt", "tenantId"}

# v3 fixed a FK/PK priority bug (PRIMARY KEY > FOREIGN KEY > UNIQUE) that v2
# got wrong for columns participating in multiple constraints. Differences in
# these fields are expected v3 improvements, not regressions.
KNOWN_V3_IMPROVEMENTS = {"isPrimary", "isForeign"}

LOOSE_COMPARE_FIELDS = {
    "schemaCount",
    "tableCount",
    "columnCount",
    "rowCount",
    "sizeBytes",
}

# System databases whose metadata changes between runs (live RDS/managed DB tables).
# Attribute diffs on these are expected and not v3 code bugs.
SYSTEM_DATABASES = {"mysql", "information_schema", "performance_schema", "sys"}


# ── Discovery ───────────────────────────────────────────────────────────────


def _discover_scenarios() -> list[str]:
    """Find scenarios that have both golden and v3 output."""
    found = []
    if not OUTPUT_DIR.is_dir():
        return found
    for d in sorted(OUTPUT_DIR.iterdir()):
        if not d.is_dir():
            continue
        golden_dir = d / "golden"
        v3_dir = d / "v3"
        has_golden = golden_dir.is_dir() and any(golden_dir.glob("*.jsonl"))
        has_v3 = v3_dir.is_dir() and any(v3_dir.glob("*.jsonl"))
        if has_golden and has_v3:
            found.append(d.name)
    return found


def _all_connection_qns() -> list[str]:
    """Collect connection QNs from integration test scenarios + common variants."""
    qns = {
        "default/mysql/e2e-test",
        "default/mysql/parity-test",
        "default/mysql/local-dev",
        "default/mysql/test",
        "default/mysql/1234567890",
    }
    try:
        # TODO(mysql-parity-port): integration class file does not yet exist.
        spec = importlib.util.spec_from_file_location(
            "test_mysql_integration",
            INTEGRATION_DIR / "test_mysql_integration.py",
        )
        assert spec is not None and spec.loader is not None
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        cls = mod.TestMySQLIntegration
        default_qn = cls.default_connection.get("connection_qualified_name", "")
        if default_qn:
            qns.add(default_qn)
        for s in cls.scenarios:
            if s.connection:
                qn = s.connection.get("connection_qualified_name", "")
                if qn:
                    qns.add(qn)
    except Exception:
        pass
    return list(qns)


V3_CONNECTION_QNS = _all_connection_qns()


# ── Helpers ─────────────────────────────────────────────────────────────────


def _load_jsonl(path: Path) -> list[dict]:
    if not path.exists():
        pytest.skip(f"Not found: {path}")
    records = []
    with open(path) as f:
        for line in f:
            if line.strip():
                records.append(json.loads(line))
    return records


def _load_records_by_typename(base: Path, typename: str) -> list[dict] | None:
    """Load every record across all ``*.jsonl`` in ``base`` whose ``typeName``
    matches. Returns ``None`` if the dir doesn't exist (caller decides skip).

    Records are bucketed by ``typeName`` rather than emitting filename so the
    comparison stays correct across the v2→v3 split (v2 packs Tables and
    Views into ``table.jsonl`` with mixed ``typeName``; v3 splits them).
    """
    if not base.is_dir():
        return None
    records: list[dict] = []
    for path in base.glob("*.jsonl"):
        with open(path) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                rec = json.loads(line)
                if rec.get("typeName") == typename:
                    records.append(rec)
    return records


def _load_golden(scenario: str, entity: str) -> list[dict]:
    base = OUTPUT_DIR / scenario / "golden"
    typename = ENTITY_TO_TYPENAME[entity]
    records = _load_records_by_typename(base, typename)
    if records is None:
        pytest.skip(f"Not found: {base}")
    return records


def _load_v3(scenario: str, entity: str) -> list[dict]:
    """Load per-scenario v3 output. Falls back to PARITY_V3_OUTPUT env var."""
    base = OUTPUT_DIR / scenario / "v3"
    typename = ENTITY_TO_TYPENAME[entity]
    records = _load_records_by_typename(base, typename)
    if records is not None:
        return records

    # Fallback: shared v3 output path (for backwards compat / manual runs)
    explicit = os.environ.get("PARITY_V3_OUTPUT")
    if explicit:
        return [_normalize(r) for r in _load_v3_raw_transformed(explicit, entity)]

    pytest.skip(
        f"No v3 output for {scenario}/{entity} — run: uv run python tests/parity/run_parity.py"
    )


def _load_v3_raw_transformed(output_path: str, entity: str) -> list[dict]:
    transformed_dir = os.path.join(output_path, "transformed")
    records = []
    entity_dir = os.path.join(transformed_dir, entity)
    if os.path.isdir(entity_dir):
        pattern = os.path.join(entity_dir, "**/*.json")
    else:
        pattern = os.path.join(transformed_dir, f"{entity}*.json")
    for json_file in sorted(_glob.glob(pattern, recursive=True)):
        if "statistics" in json_file:
            continue
        with open(json_file) as f:
            for line in f:
                if line.strip():
                    records.append(json.loads(line))
    return records


def _normalize_value(v: object) -> object:
    if isinstance(v, str):
        for cqn in V3_CONNECTION_QNS:
            if cqn in v:
                v = v.replace(cqn, CANONICAL_CONNECTION_QN)
        return v
    if isinstance(v, dict):
        return {dk: _normalize_value(dv) for dk, dv in v.items()}
    if isinstance(v, list):
        return [_normalize_value(item) for item in v]
    return v


def _normalize(record: dict) -> dict:
    attrs = record.get("attributes", {})
    cleaned = {}
    for k, v in attrs.items():
        if k in VOLATILE_FIELDS:
            continue
        cleaned[k] = _normalize_value(v)
    return {
        "typeName": record.get("typeName", ""),
        "status": record.get("status", ""),
        "attributes": cleaned,
    }


def _by_qn(records: list[dict]) -> dict[str, dict]:
    return {
        r["attributes"]["qualifiedName"]: r
        for r in records
        if r.get("attributes", {}).get("qualifiedName")
    }


def _compare_values(key: str, v2_val, v3_val) -> bool:
    if v2_val == v3_val:
        return True
    if key in LOOSE_COMPARE_FIELDS:
        try:
            return float(v2_val) == float(v3_val)
        except (ValueError, TypeError):
            pass
    if v2_val in (None, "") and v3_val in (None, ""):
        return True
    return False


# ── Parametrization ─────────────────────────────────────────────────────────

_SCENARIOS = _discover_scenarios()
_PARAMS = [(s, e) for s in _SCENARIOS for e in ENTITY_TYPES]
_IDS = [f"{s}-{e}" for s, e in _PARAMS]


# ── Tests ───────────────────────────────────────────────────────────────────


class TestParityRecordCounts:
    # Allow live DB variance on column counts: golden and v3 are captured at
    # different times so background DDL may shift counts slightly.
    _COLUMN_COUNT_TOLERANCE = 15

    @pytest.mark.parametrize("scenario,entity", _PARAMS, ids=_IDS)
    def test_record_count(self, scenario: str, entity: str) -> None:
        golden = _load_golden(scenario, entity)
        v3_records = _load_v3(scenario, entity)
        expected = len(golden)
        actual = len(v3_records)
        if entity == "column":
            assert abs(actual - expected) <= self._COLUMN_COUNT_TOLERANCE, (
                f"[{scenario}/{entity}] v2={expected}, v3={actual} "
                f"(delta: {actual - expected:+d}, tolerance: ±{self._COLUMN_COUNT_TOLERANCE})"
            )
        else:
            assert (
                actual == expected
            ), f"[{scenario}/{entity}] v2={expected}, v3={actual} (delta: {actual - expected:+d})"


class TestParityCoverage:
    @pytest.mark.parametrize("scenario,entity", _PARAMS, ids=_IDS)
    def test_all_v2_assets_in_v3(self, scenario: str, entity: str) -> None:
        golden = _load_golden(scenario, entity)
        v3_records = _load_v3(scenario, entity)
        v2_qns = {
            r["attributes"]["qualifiedName"]
            for r in golden
            if r["attributes"].get("qualifiedName")
        }
        v3_qns = {
            r["attributes"]["qualifiedName"]
            for r in v3_records
            if r["attributes"].get("qualifiedName")
        }
        missing = v2_qns - v3_qns
        assert not missing, (
            f"[{scenario}/{entity}] {len(missing)} missing:\n"
            + "\n".join(sorted(missing)[:20])
        )

    @pytest.mark.parametrize("scenario,entity", _PARAMS, ids=_IDS)
    def test_no_extra_v3_assets(self, scenario: str, entity: str) -> None:
        golden = _load_golden(scenario, entity)
        v3_records = _load_v3(scenario, entity)
        v2_qns = {
            r["attributes"]["qualifiedName"]
            for r in golden
            if r["attributes"].get("qualifiedName")
        }
        v3_qns = {
            r["attributes"]["qualifiedName"]
            for r in v3_records
            if r["attributes"].get("qualifiedName")
        }
        extra = v3_qns - v2_qns
        assert not extra, f"[{scenario}/{entity}] {len(extra)} extra:\n" + "\n".join(
            sorted(extra)[:20]
        )


class TestParityAttributes:
    @pytest.mark.parametrize("scenario,entity", _PARAMS, ids=_IDS)
    def test_attribute_parity(self, scenario: str, entity: str) -> None:
        golden = _load_golden(scenario, entity)
        v3_records = _load_v3(scenario, entity)
        v2_by_qn = _by_qn(golden)
        v3_by_qn = _by_qn(v3_records)

        diffs: list[str] = []
        for qn, v2_rec in v2_by_qn.items():
            v3_rec = v3_by_qn.get(qn)
            if not v3_rec:
                continue
            # Skip system databases — their metadata changes between runs
            qn_parts = qn.replace(CANONICAL_CONNECTION_QN + "/", "").split("/")
            if qn_parts and qn_parts[0] in SYSTEM_DATABASES:
                continue
            if v2_rec["typeName"] != v3_rec["typeName"]:
                diffs.append(
                    f"  {qn}: typeName {v2_rec['typeName']!r} -> {v3_rec['typeName']!r}"
                )
            v2_a, v3_a = v2_rec["attributes"], v3_rec["attributes"]
            for key in sorted(set(v2_a) | set(v3_a)):
                if key == "qualifiedName":
                    continue
                if key in VOLATILE_FIELDS:
                    continue
                if key in KNOWN_V3_IMPROVEMENTS:
                    continue
                if not _compare_values(key, v2_a.get(key), v3_a.get(key)):
                    diffs.append(
                        f"  {qn}.{key}: {v2_a.get(key)!r} -> {v3_a.get(key)!r}"
                    )

        if diffs:
            pytest.fail(
                f"[{scenario}/{entity}] {len(diffs)} diffs:\n" + "\n".join(diffs[:50])
            )


class TestParityTypeNames:
    @pytest.mark.parametrize("scenario,entity", _PARAMS, ids=_IDS)
    def test_typename_match(self, scenario: str, entity: str) -> None:
        golden = _load_golden(scenario, entity)
        v3_records = _load_v3(scenario, entity)
        v2_by_qn = _by_qn(golden)
        v3_by_qn = _by_qn(v3_records)
        mismatches = [
            f"  {qn}: {v2_by_qn[qn]['typeName']!r} -> {v3_by_qn[qn]['typeName']!r}"
            for qn in v2_by_qn
            if qn in v3_by_qn and v2_by_qn[qn]["typeName"] != v3_by_qn[qn]["typeName"]
        ]
        assert not mismatches, (
            f"[{scenario}/{entity}] typeName mismatches:\n" + "\n".join(mismatches)
        )
