# Accept BASE_IMAGE as a build argument
ARG BASE_IMAGE

# Use BASE_IMAGE
FROM ${BASE_IMAGE}

# necessary runtime packages
RUN microdnf upgrade -y && \
    microdnf install -y \
    tar \
    which \
    gzip \
    && microdnf clean all

# Install Dapr CLI with the specified version
RUN curl -fsSL https://raw.githubusercontent.com/dapr/cli/master/install/install.sh | DAPR_INSTALL_DIR="/usr/local/bin" /bin/bash -s 1.14.1

# Remove temporary tools
RUN microdnf remove -y \
    tar \
    gzip \
    && rm -rf /tmp/* \
    && microdnf clean all

# Install Supervisor
RUN pip install --upgrade pip && \
    pip install --no-cache-dir supervisor

# Copy Supervisord configuration
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Set default environment variables for ports
ENV ATLAN_APP_HTTP_PORT=8000
ENV ATLAN_APP_HTTP_HOST="0.0.0.0"
ENV ATLAN_DAPR_APP_PORT=3000
ENV ATLAN_DAPR_HTTP_PORT=3500
ENV ATLAN_DAPR_GRPC_PORT=50001
ENV ATLAN_DAPR_METRICS_PORT=3100
ENV OTEL_PYTHON_EXCLUDED_URLS="/telemetry/.*,/system/.*"
ENV ENABLE_OTLP_LOGS=true


# Workdir for the agent
WORKDIR /application

# Add entrypoint script
COPY entrypoint.sh entrypoint.sh
RUN chmod +x entrypoint.sh

# Start Supervisord
ENTRYPOINT [ "./entrypoint.sh" ]
