[tool.poetry]
name = "phoenix-mysql-app"
version = "0.1.0"
description = ""
authors = ["Amit Prabhu <amit.dp180@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
fastapi = {extras = ["standard"], version = "^0.115.0"}
pytest-asyncio = "^0.24.0"
# use local application-sdk repository for development
# application-sdk = { path = "../application-sdk/", develop = true, extras = ["workflows", "dashboard"]}
# use remote application-sdk repository
application-sdk = {git = "git@github.com:atlanhq/application-sdk.git", rev = "main", extras = ["workflows", "dashboard"]}
pymysql = "^1.1.1"
cryptography = "^44.0.0"

[tool.poetry.group.app.dependencies]
aiofiles = "^24.1.0"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.35"}


[tool.poetry.group.dev.dependencies]
pre-commit = "^3.8.0"
isort = "^5.13.2"


[tool.poetry.group.test.dependencies]
pytest = "^8.3.3"
coverage = "^7.6.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
venvPath = "."
venv = ".venv"
typeCheckingMode = "strict"
reportMissingTypeStubs = false

[tool.pytest.ini_options]
asyncio_mode = "auto"
