{{- define "dapr-components.data" }}
  atlan-objectstore.yaml: |
    apiVersion: dapr.io/v1alpha1
    kind: Component
    metadata:
      name: atlan-objectstore
    spec:
      type: bindings.aws.s3
      version: v1
      metadata:
        - name: bucket
          value: atlan-bucket
        - name: region
          value: us-east-1
        - name: endpoint
          value: "https://{{ .Values.global.atlanBaseUrl }}/api/blobstorage"
        - name: accessKey
        {{- if .Values.global.clientId }}
          value: "{{ .Values.global.clientId }}"
        {{- else }}
          secretKeyRef:
            {{- if .Values.dapr.components.deployment_secrets.multiKeySecretPath }}
            name: "{{ .Values.dapr.components.deployment_secrets.multiKeySecretPath }}"
            {{- else }}
            name: ATLAN_AUTH_CLIENT_ID
            {{- end }}
            key: ATLAN_AUTH_CLIENT_ID
        {{- end }}
        - name: secretKey
        {{- if .Values.global.clientSecret }}
          value: "{{ .Values.global.clientSecret }}"
        {{- else }}
          secretKeyRef:
            {{- if .Values.dapr.components.deployment_secrets.multiKeySecretPath }}
            name: "{{ .Values.dapr.components.deployment_secrets.multiKeySecretPath }}"
            {{- else }}
            name: ATLAN_AUTH_CLIENT_SECRET
            {{- end }}
            key: ATLAN_AUTH_CLIENT_SECRET
        {{- end }}
        - name: forcePathStyle
          value: "true"
    {{- if .Values.dapr.components.deployment_secrets.enabled }}
    auth:
      secretStore: deployment-secret-store
    {{- end }}
  {{- if .Values.dapr.components.objectstore.enabled }}
  objectstore.yaml: |
    apiVersion: dapr.io/v1alpha1
    kind: Component
    metadata:
      name: {{ .Values.name }}-objectstore
    spec:
      type: {{ .Values.dapr.components.objectstore.spec.type }}
      version: {{ .Values.dapr.components.objectstore.spec.version }}
      metadata:
    {{- range .Values.dapr.components.objectstore.spec.metadata }}
      - name: {{ .name }}
        value: {{ .value }}
    {{- end }}
  {{- end }}
  {{- if .Values.dapr.components.secretstore.enabled }}
  secretstore.yaml: |
    apiVersion: dapr.io/v1alpha1
    kind: Component
    metadata:
      name: secretstore
    spec:
      type: {{ .Values.dapr.components.secretstore.spec.type }}
      version: {{ .Values.dapr.components.secretstore.spec.version }}
      metadata:
    {{- range .Values.dapr.components.secretstore.spec.metadata }}
      - name: {{ .name }}
        value: {{ .value }}
    {{- end }}
  {{- end }}
  {{- if .Values.dapr.components.deployment_secrets.enabled }}
  deployment-secrets.yaml: |
    apiVersion: dapr.io/v1alpha1
    kind: Component
    metadata:
      name: deployment-secret-store
    spec:
      type: {{ .Values.dapr.components.deployment_secrets.spec.type }}
      version: {{ .Values.dapr.components.deployment_secrets.spec.version }}
  {{- end }}
  {{- if .Values.dapr.components.eventstore.enabled }}
  eventstore.yaml: |
    apiVersion: dapr.io/v1alpha1
    kind: Component
    metadata:
      name: eventstore
    spec:
      type: bindings.http
      version: v1
      metadata:
        - name: url
          value: "http://event-ingress.event-ingress-app.svc.cluster.local:8000/api/eventingress/"
  {{- end }}
{{- end }}

{{- if and .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-dapr-components
data:
  {{- include "dapr-components.data" . | nindent 2 }}
{{- end }}
