{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 8 }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
        checksum/dapr-components-config: {{ include "dapr-components.data" . | sha256sum }}
    spec:
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}

      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "app.fullname" . }}-serviceaccount
      {{- end }}

      {{- if .Values.securityContext }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: main
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.command }}
          command: {{ toYaml .Values.command | nindent 12 }}
          {{- end }}
          {{- if .Values.podSecurityContext }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              name: http
              protocol: TCP
          {{- if .Values.daprMetrics.enabled }}
            - containerPort: {{ .Values.daprMetrics.port }}
              name: dapr-metrics
              protocol: TCP
          {{- end }}
          volumeMounts:
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: dapr-components
              mountPath: /app/components
              readOnly: true
            {{- if .Values.certificates.enabled }}
            - name: certificates
              mountPath: {{ .Values.certificates.mountPath }}
              readOnly: true
            {{- end }}
          env:
            {{- include "app.envs" . | nindent 12 }}
            {{- if .Values.dapr.components.objectstore.enabled }}
            - name: DEPLOYMENT_OBJECT_STORE_NAME
              value: "{{ .Values.name }}-objectstore"
            {{- end }}
            {{- if .Values.dapr.components.secretstore.enabled }}
            - name: SECRET_STORE_NAME
              value: "secretstore"
            {{- end }}
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            - name: ATLAN_BASE_URL
              value: "https://{{ .Values.global.atlanBaseUrl  }}"
            - name: ATLAN_DOMAIN_NAME
              value: "{{ .Values.global.atlanBaseUrl }}"
            - name: ATLAN_APPLICATION_NAME
              value: "{{ .Values.name }}"
            - name: ATLAN_DEPLOYMENT_NAME
              value: '{{ if eq .Values.deploymentName "production" }}prod{{ else }}{{ .Values.deploymentName }}{{ end }}'
            - name: ATLAN_WORKFLOW_PORT
              value: "7236"
            - name: ATLAN_WORKFLOW_TLS_ENABLED
              value: "false"
            - name: ATLAN_WORKFLOW_NAMESPACE
              value: "default"
            - name: ENABLE_OTLP_LOGS
              value: "false"
            - name: ATLAN_AUTH_ENABLED
              value: "false"
            - name: ENABLE_ATLAN_UPLOAD
              value: "false"
            - name: ATLAN_ENABLE_OBSERVABILITY_DAPR_SINK
              value: "false"
            - name: UPSTREAM_OBJECT_STORE_NAME
              value: "{{ .Values.name }}-objectstore"
            - name: LOG_LEVEL
              value: "INFO"
            - name: ATLAN_APP_HTTP_PORT
              value: "8000"
            - name: ATLAN_APP_HTTP_HOST
              value: "0.0.0.0"
            - name: ATLAN_WORKFLOW_HOST
              value: "temporal-cluster-internal-frontend-headless.temporal.svc.cluster.local"
            - name: ATLAN_AUTH_URL
              value: "https://{{ .Values.global.atlanBaseUrl }}/auth/realms/default/protocol/openid-connect/token"
            {{- if .Values.global.clientId }}
            - name: ATLAN_AUTH_CLIENT_ID
              value: "{{ .Values.global.clientId }}"
            {{- end }}
            {{- if .Values.global.clientSecret }}
            - name: ATLAN_AUTH_CLIENT_SECRET
              value: "{{ .Values.global.clientSecret }}"
            {{- end }}
            {{- if .Values.certificates.enabled }}
            - name: SSL_CERT_DIR
              value: {{ .Values.certificates.mountPath | quote }}
            {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}

          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      volumes:
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: dapr-components
          configMap:
            name: {{ include "app.fullname" . }}-dapr-components
        {{- if .Values.certificates.enabled }}
        - name: certificates
          configMap:
            name: {{ .Values.certificates.configMapName }}
        {{- end }}
{{- end }}
