---
{{- if and .Values.enabled .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.fullname" . }}-serviceaccount
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
  {{- end }}
secrets:
  - name: {{ include "app.serviceAccountName" . }}-token-secret-{{ .Values.name }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ include "app.serviceAccountName" . }}-token-secret-{{ .Values.name }}
  annotations:
    kubernetes.io/service-account.name: {{ include "app.fullname" . }}-serviceaccount
{{- end }}
